modLoader="javafml"
loaderVersion="[32,)"
license="MIT"
issueTrackerURL="https://github.com/Fourmisain/TaxFreeLevels/issues"

[[mods]]
modId="taxfreelevels"
version="${version}"
displayName="Tax Free Levels"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tax-free-levels"
logoFile= "icon.png"
authors="Fourmisain"
description='''
Flattens anvil and enchantment costs above player level 30 and makes renaming items always cost 1 level.
'''

[[dependencies.taxfreelevels]]
modId="forge"
mandatory=true
versionRange="[32.0.108,)"
ordering="NONE"
side="BOTH"

[[dependencies.taxfreelevels]]
modId="minecraft"
mandatory=true
versionRange="[1.16,)"
ordering="NONE"
side="BOTH"
