modLoader="javafml"
loaderVersion="[50,)"
license="MIT"
issueTrackerURL="https://github.com/Fourmisain/TaxFreeLevels/issues"

[[mods]]
modId="taxfreelevels"
version="${mod_version}"
displayName="Tax Free Levels"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tax-free-levels"
logoFile= "icon.png"
authors="Fourmisain"
description='''
Flattens anvil and enchantment costs, removes the anvil limit and makes renaming items always cost 1 level.
'''
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.taxfreelevels]]
modId="forge"
mandatory=true
versionRange="[50.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.taxfreelevels]]
modId="minecraft"
mandatory=true
versionRange="${forge_game_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.taxfreelevels]]
modId = "cloth_config"
mandatory = true
versionRange = "[15,)"
ordering = "NONE"
side = "BOTH"
