dependencies {
	modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	modApi("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}") {
		exclude(group: "net.fabricmc.fabric-api")
	}

	modImplementation("com.terraformersmc:modmenu:${project.modmenu_version}")

	modCompileOnly "maven.modrinth:charm:${project.charm_version}"
	modCompileOnly "maven.modrinth:spectrum:${project.spectrum_version}"
	modCompileOnly "maven.modrinth:dis-enchanting-table:${project.dis_enchanting_table_version}"

	include(implementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-fabric:${project.mixinsquared_version}")))

	common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
	shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
}
