org.gradle.jvmargs=-Xmx3G
org.gradle.warning.mode=all

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.3
enabled_platforms=fabric,forge,neoforge
yarn_mappings=1.21.3+build.2
yarn_mappings_patch_neoforge_version=1.21+build.4

# Mod Properties
mod_version=1.4.20
maven_group=io.github.fourmisain
archives_base_name=TaxFreeLevels

# Dependencies
java_version=21
cloth_config_version=16.0.143

# fabric
fabric_loader_version=0.18.5
fabric_loader_version_range=>=0.15.10
fabric_api_version=0.114.0+1.21.3
modmenu_version=12.0.0
charm_version=4.1.1
spectrum_version=1.7.9

# (neo)forge
forge_version=53.0.35
mixinextras_version=0.5.4
neoforge_version=21.3.58

# publishing
modrinth_id=jCBrrLTs
curseforge_id=462128
minepkg_id=taxfreelevels
fabric_game_version_range=>=1.21.2 <=1.21.4
fabric_game_version_list=1.21.2, 1.21.3, 1.21.4
forge_game_version_range=[1.21.3, 1.21.4]
forge_game_version_list=1.21.3, 1.21.4
neoforge_game_version_range=[1.21.2, 1.21.4]
neoforge_game_version_list=1.21.2, 1.21.3, 1.21.4
modrinth_dependencies=9s6osm5g
modrinth_fabric_dependencies=P7dR8mSH
curseforge_dependencies=cloth-config
curseforge_fabric_dependencies=fabric-api
minepkg_dependencies=fabric, cloth-config
