org.gradle.jvmargs=-Xmx3G
org.gradle.warning.mode=all

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=1.21.5
enabled_platforms=fabric,neoforge
yarn_mappings=1.21.5+build.1
yarn_mappings_patch_neoforge_version=1.21+build.4

# Mod Properties
mod_version=1.4.24
maven_group=io.github.fourmisain
archives_base_name=TaxFreeLevels

# Dependencies
java_version=21
cloth_config_version=20.0.148
mixinsquared_version=0.3.7-beta.3

# fabric
fabric_loader_version=0.18.5
fabric_loader_version_range=>=0.16
fabric_api_version=0.119.5+1.21.5
modmenu_version=16.0.0-rc.1
charm_version=4.1.1
spectrum_version=1.7.9
fixed_version=1.6.2-1.21.11

# neoforge
neoforge_version=21.5.73-beta

# publishing
modrinth_id=jCBrrLTs
curseforge_id=462128
minepkg_id=taxfreelevels
fabric_game_version_range=>=1.21.5 <=1.21.8
fabric_game_version_list=1.21.5, 1.21.6, 1.21.7, 1.21.8
neoforge_game_version_range=[1.21.5, 1.21.8]
neoforge_game_version_list=1.21.5, 1.21.6, 1.21.7, 1.21.8
modrinth_dependencies=9s6osm5g
modrinth_fabric_dependencies=P7dR8mSH
curseforge_dependencies=cloth-config
curseforge_fabric_dependencies=fabric-api
minepkg_dependencies=fabric, cloth-config
