modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/Fourmisain/TaxFreeLevels/issues"

[[mods]]
modId = "taxfreelevels"
version = "${mod_version}"
displayName = "Tax Free Levels"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/tax-free-levels"
logoFile = "icon.png"
authors = "Fourmisain"
description = '''
Flattens anvil and enchantment costs above player level 30 and makes renaming items always cost 1 level.
'''
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.taxfreelevels]]
modId = "neoforge"
mandatory = true
versionRange = "[20.5.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.taxfreelevels]]
modId = "minecraft"
mandatory = true
versionRange = "${neoforge_game_version_range}"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "taxfreelevels-neoforge.mixins.json"
