modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/Fourmisain/TaxFreeLevels/issues"

[[mods]]
modId = "taxfreelevels"
version = "${mod_version}"
displayName = "Tax Free Levels"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/tax-free-levels"
logoFile = "icon.png"
authors = "Fourmisain"
description = '''
Flattens anvil and enchantment costs, removes the anvil limit and makes renaming items always cost 1 level.
'''

[[dependencies.taxfreelevels]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.143,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.taxfreelevels]]
modId = "minecraft"
type = "required"
versionRange = "${neoforge_game_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.taxfreelevels]]
modId = "cloth_config"
type = "required"
versionRange = "[15,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "taxfreelevels-common-neoforge.mixins.json"

[[mixins]]
config = "taxfreelevels-neoforge.mixins.json"
